# Generated by Django 3.0 on 2020-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('intro', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('areaCode', models.IntegerField()),
                ('sigunguCode', models.IntegerField()),
            ],
        ),
    ]
