# Generated by Django 3.0 on 2020-11-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rand_place_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
